### PR TITLE
Remove frame, use context for every drawing

### PR DESCRIPTION
**Pull request by zxey**
I removed Frame for drawing paths and put path function into Context struct to be more in line with the c api of nanovg, but I wanted some feedback, because I don't know if this is the right way.

What was my intention with this, is when you have function for drawing some composite shape or widget, I wanted it to be more straightforward.
Example:
I wanted this:
```
fn button(context: &Context, ......) {
    context.path(|path| {
        path.rect(...);
    });
    context.text(...);
}
```
Instead of this:
```
fn button(frame: &Frame, ......) {
    frame.path(|path| {
        path.rect(...);
    });
    frame.context().text(...);
}
```
What I don't like here is the indirection.
I considered putting everything into Frame and keeping only .frame function in Context, but then I looked at the c-api and saw that everything takes context, there is no frame struct, only beginFrame, endFrame functions.

So I would like an opinion on this, if you think it's not worth it, feel free to close this PR.

### CODE REVIEW

**Comment by Lisoph** [comment]
I'm against this. The idea of the context struct is to guarantee that the drawing operations aren't performed without a call to `nvgBeginFrame`, which nanovg mandates. I'd like to avoid incorrect use of the nanovg API by binding the semantics of nanovg to Rust's type system.

I don't think a call to `context()` is too bad of an indirection. It's just more to type, the compiler will most definitely inline it.

**Comment by zxey** [comment]
Thank you for looking at this, so what do you think about moving text(), text_box() and friends into Frame? Is it valid to use these outside of frame? I quickly looked though nanovg source and by the looks of it, these functions use pixelDeviceRatio which is specified in frame, so this could probably be another option, if I am not missing anything.

**Comment by KevinKelley** [comment]
I think it's good using Frame to wrap the begin/end, like @Lisoph says... as far as moving the text() fns there, it might make sense.  But.  It's been a while and maybe I'm wrong, or things changed... but don't the text functions in NanoVG NOT respect the frame/transform/clipping?  That makes me sad... but I think it was deliberate choice, and therefore maybe we can't do this.

**Comment by Lisoph** [comment]
> don't the text functions in NanoVG NOT respect the frame/transform/clipping?

Yes, this is my understanding as well. I put the text drawing functions inside Context because nanovg's text drawing is independent from frames.

**Comment by zxey** [comment]
So I finally had the time to look more into this, and nanovg supports transform and clipping of text, but we do not allow it in nanovg-rs, I created simple test case where I added transform code to `Context::text` function (only this function for now) and TextOptions in the same way as it is in `path` (and PathOptions) and it works nicely. 
You can check it out [here](https://github.com/zxey/nanovg-rs), I have it in my fork in master branch, it is example called `demo-text` (in the demo move mouse inside the center rectangle to see how transform gets applied to text and how it gets clipped when outside this rectangle).
The next step would probably be to add transform code to all text function (I can prepare PR) and then we can maybe move them into Frame struct?

**Comment by KevinKelley** [comment]
Nice... I haven't looked at the code, just pulled and ran the example, and it looks like you're right, clearly you're getting transform and clipping of text!  So that's good, as far as I'm concerned this is something we need.

**Comment by Lisoph** [comment]
Hey @KevinKelley, did you merge this PR on purpose? Because this PR contains the "disputed removal" of the `Context` struct. @zxey hasn't submited a PR for his text transforms yet, it's only in [his fork](https://github.com/zxey/nanovg-rs) for now. Did you want to merge that instead?

**Comment by KevinKelley** [comment]
I got click-happy, and wasn't sure exactly what I was pulling. I wanted to get his demo into the codebase, but my git-fu is not the best.  I was hoping that the big green button would get me the result I wanted...

**Comment by KevinKelley** [comment]
...maybe I'm stupid.  I would like to revert my latest pull, because it was for the PR that we hadn't decided was right; and request a PR for @zxey 's latest.  But git is giving me grief.

**Comment by zxey** [comment]
I created new PR (#57) that reverts this change and moves the drawing to frame, once this is merged, I will create new PR containing the demo and finished text transforms (I have them ready if you want to look - it is the text-transform branch) after #57 gets merged.

**Pull request merged**
