### PR TITLE
Update nanovg-rs to work with the current Rust and Cargo nightlies

### PR DESCRIPTION
**Pull request by genbattle**
First, sorry for the huge pull request, I know how much of a pain these are to receive and review.

It's taken a couple of weeks, but I finally managed to catch up with the latest Rust and Cargo builds and compile/run without errors, and mostly without warnings. I've disabled the "unstable" warnings, because for the most part there's nothing that can be done with them, e.g.:
```
src/demo.rs:53:65: 53:75 warning: use of unstable item: Instead of taking this bound generically, this trait will be replaced with one of slicing syntax (&foo[]), deref coercions, or a more generic conversion trait, #[warn(unstable)] on by default
```

I did a pretty hacky job of updating the build, but it really needs a more complete (and separate) overhaul to re-align it with Rust/Cargo best practices. I've basically used the new build.rs build system just to wrap the old build system as an adapter and updated a few environment variables in the premake script, but theoretically it should be possible to completely eliminate the .mk file and rely completely on the build.rs script (read more [here](http://doc.crates.io/build-script.html)).

### CODE REVIEW

**Comment by genbattle** [comment]
For an instant in time I _was_ up to date and had everything working.

The Rust team just deprecated/moved the entire io module to old_io last night -_-

The worst part is that they've done so without having any replacement immediately available. For now we'll have to depend on std::old_io instead. Even then, currently all of the dependencies for nanovg-rs all use std::io, so it still won't compile...

I'll fix the io->old_io conversion in this repo and then we just have to wait for dependencies to fix the issue. By which time I'm sure another breaking change will come down the pipeline :)

**Comment by genbattle** [comment]
Fixed the new errors and warnings in the main lib.

Turns out I just needed to update my dependencies with cargo update. The examples now compile and run with the latest nightly too.

**Comment by KevinKelley** [comment]
Thank you so much for this, it's been bugging me that I haven't had time to work on it.

**Comment by genbattle** [comment]
No problem, happy to help :)

**Pull request merged**
