### PR TITLE
add options to `TextBreakLines`

### LINKED ISSUE #78: `text_break_lines` gives different results based on most recend call to `text`
This is unexpected behavior and should at least be documented, but preferably changed.
I assume, it just has been forgotten to add,  since almost all other functions take a font and some text options, which are passed to private function `text_prepare`. So just adding a font and text options as parameters here as well should solve this issue.

### PR DESCRIPTION
**Pull request by porky11**
fixes #78

### CODE REVIEW

**Comment by porky11** [comment]
I assume, `text_glyph_positions` should call `text_prepare` as well.

**Comment by porky11** [comment]
I did a few updates, I wonder why it still fails. `cargo test` works well.

**Comment by porky11** [comment]
@KevinKelley will you merge this and publish it on crates.io?
If you don't want to, you might want to give me the rights to do so myself.

**Comment by KevinKelley** [comment]
I got covid-stranded for a couple months here...sorry.  I've just finally got access back.  I'll look at it tomorrow or so.  I'm absolutely in favor of having this fixed.

**Comment by KevinKelley** [comment]
> @KevinKelley will you merge this and publish it on crates.io?
> If you don't want to, you might want to give me the rights to do so

**Pull request merged**
