### PR TITLE
The Rewrite

### PR DESCRIPTION
**Pull request by Lisoph**
I have been working on a more-or-less total rewrite of this crate for a while now. The big idea with my rewrite is that it provides a more rust-idiomatic API (check out the example). I'd like to request to pull these changes, preferably into a new branch called `rewrite`.

The rewrite is not finished yet. There is still some functionality left to implement (like font rendering) and some other functions. Also, a lot of testing needs to be done. Therefore, I highly recommend to checkout a new branch `rewrite` and pull these changes into that branch, to avoid polluting `master` with broken code.

---

This is probably a good moment to note that this is my first pull request on GitHub, so I'm not 100% familiar with how this works. Help is appreciated!

### CODE REVIEW

**Comment by Lisoph** [comment]
The rewrite is pretty much complete. Feel free to review the changes.

I'd like to merge the rewrite back into the original repository, becase otherwise we would have to publish a new crate which would cause crate fragmentation.

**Comment by Lisoph** [comment]
Awesome, thanks! Can't wait until it's merged! ;)

**Comment by Lisoph** [comment]
Not to be rude, but how's the pull coming along? 😀

**Comment by zxey** [comment]
Would love to see this getting merged, looks nice.

**Comment by Lisoph** [comment]
🎉

In preparation for publishing the new version to crates.io, I added some fields to the [package] section in Cargo.toml. I'll create a new pull request to merge these changes.

**Pull request merged**
