### PR TITLE
[WIP] Reimplement widgets'n stuff demo

### PR DESCRIPTION
**Pull request by zxey**
I reimplemented original demo from memononen/nanovg with new api in KevinKelley/nanovg-rs.
It is function by function reimplementation. 
Almost everything is done but i could not get the scissor part of demo working. I need a bit of help, if someone knows how to get it to work, I would be very glad if we can get this merged. 

The scissor part, that does not work, can be found here: https://github.com/zxey/nanovg-rs/blob/320eccb2f7c49054df4efc28744ebf36b84c4c93/examples/demo-ui.rs#L984

The original working code is here: https://github.com/memononen/nanovg/blob/e70a78e42e781bc73393afe47a62e6c049197a0b/example/demo.c#L1027

I've tried different ways how to pass rectangle scissor and then intersect scissor, but none of them seem to work. 

I also found that you cannot translate Transform more than one time (the translates are not accumulated as it is in c version of nanovg) as seen here: 
https://github.com/zxey/nanovg-rs/blob/320eccb2f7c49054df4efc28744ebf36b84c4c93/examples/demo-ui.rs#L1017 
the workaround is to just increment the previous position as seen on the next line.
Explained in code:
```
let transform = Transform::new().translate(20.0, 10.0);
// now transform is at (x: 20.0, y: 10.0)
let transform = transform.translate(10.0, 0.0);
// now transform is at (x: 10.0, y: 0.0), expected: (x: 30.0, y: 10.0)
```
Here you can see the animation of this demo: https://gfycat.com/PoliteMeaslyItaliangreyhound in bottom left you can see that the two rectangles (red and yellow) are not clipped properly.

You can run the demo with `cargo run --example demo-ui --features "gl3"`

### CODE REVIEW

**Comment by Lisoph** [comment]
Hi @zxey, thanks for all the great contributions, you are very helpful! Stellar work on porting the demo!

> I also found that you cannot translate Transform more than one time (the translates are not accumulated as it is in c version of nanovg) as seen here:

This is true. I did this on purpose to eliminate all global state whereever possible. All paths behave like they have their own unique transform, instead of referencing a globally shared one. You can see how I did it [here](https://github.com/KevinKelley/nanovg-rs/blob/7babee1bd1fb5a5fa90f37d57106eaff6f026444/src/lib.rs#L483).

Because I reset the global transform every time, the scissors (normal and intersected) never get transformed - they are always (or should be) at the coordinate system identity. This means  that the scissors have to be calculated manually. I did this thinking that such calculations are better suited for dedicated linear algebra libraries (like cgmath or nalgebra) anyway <sup>1</sup>. Same thinking for `Transform`.

Intersections should work because I don't reset the scissor itself, so nanovg can calculate the resulting scissor from the `Scissor::Intersect` and the previous one.

> I also found that you cannot translate Transform more than one time (the translates are not accumulated as it is in c version of nanovg) as seen here

Ditto. That's honestly just a mess up on my part. The functions on `Transform` are really badly named. One might think that those are either getters, or that they **add** to the transform, like their verb name would convey. However, they actually set the transform - they are setters. Therefore no accumulating of the transform takes place.

---

I'm going to rework the Transform struct to fix these ambiguities and to add some functionality. I will also update `Scissor` as well, because it doesn't really make sense that the transform get's resetted for every path while the scissor does not.

Thanks for pointing out these problems!

<sup>1: This actually causes a massive problem: Scissors can't be rotated at all. Since they are just a rectangle with an origin and size, even linear algebra libraries can't be used! Needs to be fixed.</sup>

**Comment by zxey** [comment]
Thanks for looking into this and thanks for the kind words!
One solution to the transform problem I could think of was something along the lines that you can transform drawn paths and applied scissoring in closure in the same way you draw paths.

Code explaining what I mean:
```
let translate = Transform::new().translate(x, y);
frame.transform(translate, || {
    // here ale drawings would get translated with 'translate' Transform
    frame.path(...);
});
```
This would apply selected transform to everything in closure function and restored previous tranform after it would completed.
But I think this would be a pretty big change.
Also I don't know if it would solve all problems.

The other solution I can think of would be to be able to store state which saves transform, scissors and other properties, and allow to pass this state to drawing functions or apply it in similar way to the first solution.

**Comment by Lisoph** [comment]
I haven't read your reply yet @zxey, but I'm letting you and everyone else know that I have started with updating the Transform struct. I have create a new branch **transform_scissor** for this.

**Comment by zxey** [comment]
Okay, I also created separate issue #45, I encountered while porting this demo.

**Comment by Lisoph** [comment]
Awesome, thanks for the report! I also created an issue #46 for tracking progress.

**Comment by KevinKelley** [comment]
@Lisoph 
> The functions on Transform are really badly named. One might think that those are either getters, or that they add to the transform, like their verb name would convey. However, they actually set the transform - they are setters.

Yah... in fact that's what I did think, that they did what the names imply: modify **self** with the given rotation/translation/scale.  I think that's what they should do, given their verb names...

...but there's the functional approach as well, where values are immutable and methods like this will instead return a new Transform:  could be methods named **rotated**/**translated**/**scaled**.  Unless there's a strong reason I generally prefer that approach, treating values as immutable where possible... 

...anyway yes, good comments and let's see what we can do

**Comment by KevinKelley** [comment]
I want to merge this in (demo-ui)... I think we need a visible indicator that things are working, and this covers some things that we've changed, and in fact brings out a couple issues, as the discussion here shows.  I suggest we keep this demo active, and use it as a further test of the library.  

I'm still not sure that butts are working as intended, they seem funny to me... the wide zigzaggy lines, as they rotate, seem to change shape, that doesn't seem right

**Comment by zxey** [comment]
> I'm still not sure that butts are working as intended, they seem funny to me... the wide zigzaggy lines, as they rotate, seem to change shape, that doesn't seem right

I first thought so too, but they are working same as it is in c version of this demo.
The reason why it seems strange is because when drawing Miter line joins, the join gets cut because of miter_limit specified in StrokeStyle, but this is the intended behavior.

**Comment by KevinKelley** [comment]
@zxey sounds right, and it's good to see it in action :)

**Pull request merged**
